### ISSUE TITLE
Find references for the best infrastructure

### ISSUE THREAD

**Issue by fannyhasbi** [cerc-undip/tandera#1]
The result of this task is to get the best infrastructure for this framework

**Comment by fannyhasbi** [comment]
@fmmochtar

**Comment by fmmochtar** [comment]
Database: MongoDB or PostgreSQL
Backend: Go
Frontend: React
API: REST

Topology setup:
Frontend ---- ( API ----- Backend )

Not fixed yet. This is just a probability. Awaiting further instructions.

Docker setup: yes
Kubernetes support: dunno

**Comment by fannyhasbi** [comment]
Should we consider using Docker?

**Comment by fmmochtar** [comment]
yes. that would be a good idea.
I'm awaiting your programming language choices for both backend and frontend lol. keep me updated.

**Comment by fannyhasbi** [comment]
Choosen programming language is in this issues :
* #2 for backend
* #4 for frontend
