### ISSUE TITLE
Write list of features for project

### ISSUE THREAD

**Issue by fmmochtar** [cerc-undip/tandera#5]

**Comment by abdarafi** [comment]
## Auth
- Registration, Login, Forgot Password
## Dashboards
1. Admin Dashboard
 - Create challenges with its score, categories, hints, and flags
2. Score Dashboard
3. Challenges Dashboard

**Comment by fannyhasbi** [comment]
Should the challenges only accessible by registered users only or publicly accessible?

**Comment by abdarafi** [comment]
> Should the challenges only accessible by registered users only or publicly accessible?

The challenges can be seen for registered users only. Because of the confidentiality consideration of the challenges.
