### ISSUE TITLE
Base code for Frontend

### ISSUE THREAD

**Issue by fannyhasbi** [cerc-undip/tandera#9]
- [x] React base
- [x] Decide UI template/library. Options are:
  - Semantic UI React
  - Fluent UI React

**Comment by sayyidyofa** [comment]
Frontend base code is decided to use React with Typescript and Semantic UI React for UI library. Fixed on commit da430f929816a5656f960fa6c938cc34293fcad3 and 9df4c19db9d81206fa94b467507adacb91daad0c
